const tasks = [
  "🎯 Mission 1: Go to Veeranam and deliver a 20-second mock lecture on 'Why Monday classes should be illegal.' Record your best professor impression.",
  "🚶 Mission 2: Walk from Spice Route to Satvik while holding a straight face — no smiles, no laughs. If someone cracks you up, restart.",
  "📚 Mission 3: In the Resource Center, pick a random book and read one line out loud dramatically. Bonus if someone looks up.",
  "☕ Mission 4: Grab a chai at TOI and talk to a stranger about their most chaotic group project ever.",
  "💡 Mission 5: Stand near the Vivekananda statue and share your 'Monday Motivation' to the wind like an influencer reel.",
  "📸 Mission 6: Click a photo of your reflection on the Academic Block glass and caption it 'Future CEO loading...'.",
  "🎭 Mission 7: Recreate a Shark Tank pitch with your team in Manasarovar. Props allowed. Drama encouraged.",
  "🍽️ Mission 8: Order the weirdest combo possible at Spice Route and convince someone else to take the first bite.",
  "👥 Mission 9: Gather 3 people in the ARR lawn and start a spontaneous 'clap wave' until strangers join in.",
  "🤳 Mission 10: Take a group selfie at Kaveri Hostel entrance titled 'When deadlines meet breakdowns.'",
  "💬 Mission 11: At Chatterbox, start a conversation using only management buzzwords — 'synergy,' 'leverage,' 'touch base' — you get the idea.",
  "🎬 Mission 12: Record a 15-second motivational reel at Vivekananda statue pretending to be a life coach.",
  "🧘 Mission 13: Sit quietly in front of the Resource Center for 2 minutes. No phone. Just vibes. Post a zen caption.",
  "🎤 Mission 14: At Charlie’s Den, perform a fake TED Talk titled 'Surviving Group Assignments 101.'",
  "📊 Mission 15: On a classroom whiteboard (Erie, Michigan, or Ontario), draw your version of a 'Success Equation.'",
  "🎧 Mission 16: Plug in your earphones, walk confidently through the Academic Block like you’re in a movie montage.",
  "🎯 Mission 17: Create a mini treasure hunt clue using Digii Campus terms (attendance, assignment, output). Share it with a friend.",
  "🏃 Mission 18: Race a friend from TOI to ARR and yell 'Break-even achieved!' at the finish line.",
  "📱 Mission 19: Open Instagram at Spice Route and record a 'fake podcast' with someone about your weirdest case competition.",
  "🌅 Mission 20: Watch the sunset from Mahabalipuram and record a slow-mo walk — MBA life never looked so peaceful.",
  "🎯 Mission 21: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 22: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 23: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 24: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 25: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 26: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 27: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 28: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 29: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 30: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 31: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 32: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 33: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 34: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 35: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 36: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 37: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 38: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 39: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 40: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 41: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 42: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 43: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 44: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 45: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 46: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 47: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 48: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 49: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 50: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 51: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 52: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 53: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 54: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 55: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 56: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 57: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 58: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 59: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 60: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 61: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 62: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 63: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 64: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 65: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 66: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 67: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 68: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 69: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 70: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 71: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 72: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 73: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 74: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 75: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 76: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 77: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 78: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 79: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 80: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 81: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 82: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 83: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 84: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 85: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 86: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 87: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 88: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 89: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 90: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 91: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 92: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 93: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 94: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 95: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 96: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 97: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 98: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 99: Create a random fun challenge around campus — your creativity counts more than the task itself.",
  "🎯 Mission 100: Create a random fun challenge around campus — your creativity counts more than the task itself."
];